import type { MealPrepTemplate } from '@/types';

export const STARTER_MEAL_PREP_TEMPLATES: readonly MealPrepTemplate[] = [
  {
    id: 'rice-cooker-chicken-rice',
    title: 'One-Pot Chicken & Fragrant Rice',
    portions: 3,
    durationMinutes: 35,
    requiredAppliances: ['rice_cooker'],
    ingredients: [
      { canonicalId: 'chicken-breast', name: 'Chicken breast', quantity: 400, unit: 'g' },
      { canonicalId: 'jasmine-rice', name: 'White rice', quantity: 300, unit: 'g' },
      { canonicalId: 'soy-sauce-light', name: 'Soy sauce', quantity: 30, unit: 'ml' },
      { canonicalId: 'garlic', name: 'Garlic', quantity: 2, unit: 'piece', optional: true },
    ],
    steps: [
      {
        stepNumber: 1,
        instruction: 'Rinse rice and add to rice cooker bowl with water.',
        applianceId: null,
        actionType: 'prep',
      },
      {
        stepNumber: 2,
        instruction: 'Slice chicken breast, season with soy sauce and minced garlic, and place on top of rice.',
        applianceId: null,
        actionType: 'prep',
      },
      {
        stepNumber: 3,
        instruction: 'Start standard rice cooking cycle.',
        applianceId: 'rice_cooker',
        actionType: 'cook',
        durationMinutes: 30,
      },
      {
        stepNumber: 4,
        instruction: 'Let steam 5 minutes after cooking finishes, then divide into 3 portions.',
        applianceId: null,
        actionType: 'store',
        durationMinutes: 5,
      },
    ],
    dietaryTags: ['dairy_free'],
  },
  {
    id: 'sheet-pan-roasted-chicken-veg',
    title: 'Sheet Pan Roasted Chicken & Broccoli',
    portions: 4,
    durationMinutes: 30,
    requiredAppliances: ['oven'],
    ingredients: [
      { canonicalId: 'chicken-breast', name: 'Chicken breast', quantity: 500, unit: 'g' },
      { canonicalId: 'broccoli', name: 'Broccoli', quantity: 300, unit: 'g' },
      { canonicalId: 'olive-oil', name: 'Olive oil', quantity: 20, unit: 'ml' },
      { canonicalId: 'garlic', name: 'Garlic', quantity: 3, unit: 'piece', optional: true },
    ],
    steps: [
      {
        stepNumber: 1,
        instruction: 'Preheat oven to 200°C (400°F). Line a large baking sheet.',
        applianceId: 'oven',
        actionType: 'prep',
        durationMinutes: 5,
      },
      {
        stepNumber: 2,
        instruction: 'Cut chicken into strips and broccoli into florets. Toss with olive oil and minced garlic.',
        applianceId: null,
        actionType: 'prep',
        durationMinutes: 5,
      },
      {
        stepNumber: 3,
        instruction: 'Roast in the oven for 20 minutes until chicken is cooked through and broccoli edges are crisp.',
        applianceId: 'oven',
        actionType: 'cook',
        durationMinutes: 20,
      },
      {
        stepNumber: 4,
        instruction: 'Divide evenly into 4 meal prep containers.',
        applianceId: null,
        actionType: 'store',
      },
    ],
    dietaryTags: ['dairy_free', 'gluten_free'],
  },
  {
    id: 'air-fryer-crispy-tofu-bowl',
    title: 'Crispy Air-Fried Tofu & Veggie Bowl',
    portions: 2,
    durationMinutes: 20,
    requiredAppliances: ['air_fryer'],
    ingredients: [
      { canonicalId: 'tofu-firm', name: 'Firm tofu', quantity: 300, unit: 'g' },
      { canonicalId: 'broccoli', name: 'Broccoli', quantity: 200, unit: 'g' },
      { canonicalId: 'soy-sauce-light', name: 'Soy sauce', quantity: 20, unit: 'ml' },
      { canonicalId: 'olive-oil', name: 'Olive oil', quantity: 10, unit: 'ml' },
    ],
    steps: [
      {
        stepNumber: 1,
        instruction: 'Press and cube tofu. Cut broccoli into small florets. Toss both with soy sauce and olive oil.',
        applianceId: null,
        actionType: 'prep',
        durationMinutes: 5,
      },
      {
        stepNumber: 2,
        instruction: 'Preheat air fryer to 190°C (375°F).',
        applianceId: 'air_fryer',
        actionType: 'prep',
        durationMinutes: 3,
      },
      {
        stepNumber: 3,
        instruction: 'Air fry for 15 minutes, shaking the basket halfway through until golden and crispy.',
        applianceId: 'air_fryer',
        actionType: 'cook',
        durationMinutes: 15,
      },
      {
        stepNumber: 4,
        instruction: 'Divide into 2 containers and let cool before storing.',
        applianceId: null,
        actionType: 'store',
      },
    ],
    dietaryTags: ['vegan', 'vegetarian', 'dairy_free'],
  },
  {
    id: 'stovetop-egg-fried-rice',
    title: 'Classic Egg & Veggie Fried Rice',
    portions: 2,
    durationMinutes: 15,
    requiredAppliances: ['cooktop'],
    ingredients: [
      { canonicalId: 'jasmine-rice', name: 'Cooked rice', quantity: 300, unit: 'g' },
      { canonicalId: 'eggs', name: 'Eggs', quantity: 3, unit: 'piece' },
      { canonicalId: 'soy-sauce-light', name: 'Soy sauce', quantity: 20, unit: 'ml' },
      { canonicalId: 'garlic', name: 'Garlic', quantity: 2, unit: 'piece', optional: true },
      { canonicalId: 'olive-oil', name: 'Cooking oil', quantity: 15, unit: 'ml' },
    ],
    steps: [
      {
        stepNumber: 1,
        instruction: 'Whisk eggs in a small bowl. Mince garlic.',
        applianceId: null,
        actionType: 'prep',
        durationMinutes: 3,
      },
      {
        stepNumber: 2,
        instruction: 'Heat pan over medium-high heat with oil. Scramble eggs softly and set aside.',
        applianceId: 'cooktop',
        actionType: 'cook',
        durationMinutes: 2,
      },
      {
        stepNumber: 3,
        instruction: 'Sauté garlic, add rice, drizzle soy sauce, and stir-fry for 5 minutes.',
        applianceId: 'cooktop',
        actionType: 'cook',
        durationMinutes: 5,
      },
      {
        stepNumber: 4,
        instruction: 'Fold in eggs, mix well, and pack into 2 meal prep boxes.',
        applianceId: 'cooktop',
        actionType: 'assemble',
        durationMinutes: 2,
      },
    ],
    dietaryTags: ['vegetarian', 'dairy_free'],
  },
  {
    id: 'slow-cooker-chicken-stew',
    title: 'Slow Cooker Hearty Chicken & Potato Stew',
    portions: 4,
    durationMinutes: 240,
    requiredAppliances: ['slow_cooker'],
    ingredients: [
      { canonicalId: 'chicken-breast', name: 'Chicken breast', quantity: 500, unit: 'g' },
      { canonicalId: 'potato', name: 'Potatoes', quantity: 400, unit: 'g' },
      { canonicalId: 'yellow-onion', name: 'Onions', quantity: 2, unit: 'piece' },
      { canonicalId: 'garlic', name: 'Garlic', quantity: 3, unit: 'piece', optional: true },
    ],
    steps: [
      {
        stepNumber: 1,
        instruction: 'Chop chicken, potatoes, and onions into bite-sized chunks.',
        applianceId: null,
        actionType: 'prep',
        durationMinutes: 10,
      },
      {
        stepNumber: 2,
        instruction: 'Place all ingredients into the slow cooker bowl with 2 cups of water or stock and minced garlic.',
        applianceId: null,
        actionType: 'assemble',
      },
      {
        stepNumber: 3,
        instruction: 'Cover and cook on Low for 4 hours (or High for 2.5 hours) until vegetables are tender.',
        applianceId: 'slow_cooker',
        actionType: 'cook',
        durationMinutes: 240,
      },
      {
        stepNumber: 4,
        instruction: 'Ladle into 4 meal prep containers.',
        applianceId: null,
        actionType: 'store',
      },
    ],
    dietaryTags: ['dairy_free', 'gluten_free'],
  },
  {
    id: 'no-cook-tofu-cucumber-bowl',
    title: 'Cold Sesame-Soy Tofu & Cucumber Bowl',
    portions: 2,
    durationMinutes: 10,
    requiredAppliances: [],
    ingredients: [
      { canonicalId: 'tofu-firm', name: 'Firm tofu', quantity: 300, unit: 'g' },
      { canonicalId: 'cucumber', name: 'Cucumber', quantity: 2, unit: 'piece' },
      { canonicalId: 'soy-sauce-light', name: 'Soy sauce', quantity: 20, unit: 'ml' },
      { canonicalId: 'garlic', name: 'Garlic', quantity: 1, unit: 'piece', optional: true },
    ],
    steps: [
      {
        stepNumber: 1,
        instruction: 'Drain tofu and cut into clean bite-sized cubes.',
        applianceId: null,
        actionType: 'prep',
        durationMinutes: 3,
      },
      {
        stepNumber: 2,
        instruction: 'Thinly slice cucumbers into ribbons or rounds.',
        applianceId: null,
        actionType: 'prep',
        durationMinutes: 3,
      },
      {
        stepNumber: 3,
        instruction: 'Whisk soy sauce and finely grated garlic in a small dish.',
        applianceId: null,
        actionType: 'prep',
        durationMinutes: 2,
      },
      {
        stepNumber: 4,
        instruction: 'Layer tofu and cucumbers into containers and spoon dressing over top.',
        applianceId: null,
        actionType: 'assemble',
        durationMinutes: 2,
      },
    ],
    dietaryTags: ['vegan', 'vegetarian', 'dairy_free'],
  },
  {
    id: 'microwave-steamed-salmon-greens',
    title: 'Quick Steamed Salmon & Broccoli',
    portions: 1,
    durationMinutes: 8,
    requiredAppliances: ['microwave'],
    ingredients: [
      { canonicalId: 'salmon', name: 'Salmon', quantity: 180, unit: 'g' },
      { canonicalId: 'broccoli', name: 'Broccoli', quantity: 150, unit: 'g' },
      { canonicalId: 'soy-sauce-light', name: 'Soy sauce', quantity: 15, unit: 'ml' },
    ],
    steps: [
      {
        stepNumber: 1,
        instruction: 'Place salmon and broccoli in a microwave-safe container with 1 tbsp water.',
        applianceId: null,
        actionType: 'prep',
        durationMinutes: 2,
      },
      {
        stepNumber: 2,
        instruction: 'Drizzle with light soy sauce and cover with a microwave-safe vented lid.',
        applianceId: null,
        actionType: 'prep',
        durationMinutes: 1,
      },
      {
        stepNumber: 3,
        instruction: 'Microwave on high power for 4–5 minutes until salmon is tender and cooked through.',
        applianceId: 'microwave',
        actionType: 'cook',
        durationMinutes: 5,
      },
      {
        stepNumber: 4,
        instruction: 'Let stand for 1 minute before serving or storing.',
        applianceId: null,
        actionType: 'store',
      },
    ],
    dietaryTags: ['dairy_free', 'gluten_free'],
  },
];
